refactor: Migrate AssetHeader to React
wireapp/wire-webapp pull request #10327
Opened 2021-01-21 15:19 UTC by ffflorian

2021-01-21 15:23 UTC, thisisamir98 commented on src/script/main/globals.ts
> +import 'Components/infoToggle';
```suggestion
import 'Components/InfoToggle';
```

2021-01-21 15:24 UTC, thisisamir98 commented on src/script/components/asset/AssetHeader.tsx
>    `,
are we keeping this?

2021-01-21 15:54 UTC, thisisamir98 approved these changes

2021-01-21 16:03 UTC, ffflorian commented on src/script/components/asset/AssetHeader.test.tsx
> +    // expect(assetHeader.getTime()).toBe('01/21 4:08 PM');
TODO

2021-01-22 10:16 UTC, bennycode requested changes
The `data-uie-name` value should be unique.

2021-01-22 10:16 UTC, bennycode commented on src/script/components/asset/AssetHeader.tsx
> +      <span className={cx('asset-header-name', message.accent_color)} data-uie-name="user-name">
```suggestion
      <span className={cx('asset-header-name', message.accent_color)} data-uie-name="asset-header-user-name">
```

2021-01-22 10:16 UTC, bennycode commented on src/script/components/asset/AssetHeader.tsx
> +      <span className="asset-header-time" data-uie-name="header-time">
```suggestion
      <span className="asset-header-time" data-uie-name="asset-header-time">
```

2021-01-22 10:45 UTC, bennycode approved these changes

2021-01-22 11:19 UTC, merged