chore: Base tag information on script input rather than branch name
wireapp/wire-webapp pull request #11336
Opened 2021-06-23 17:03 UTC by lucendio

The container image tag information are now solely defined by the script input.
Due to the fact that branch information are not available during the release
process (because it indicated by a tag), it make sense to rather base the tag
determination on the stageParam, which is set i the respective pipeline step.

This also allows to further simplify the script assembling that tag and pushing
the images. Alongside, some variables have been renamed to clarify the meaning
of their values.
The pipelines uses 7 characters while the script only used 6 (second param of
substring behaves exclusive). This has been aligned.

*Owner: @arianvp*

2021-06-28 12:25 UTC, arianvp approved these changes
At first glance this looks ok to me

2021-07-08 13:34 UTC, ffflorian requested changes

2021-07-08 13:34 UTC, ffflorian commented on bin/push_docker.js
> +  distributionParam ? distributionParam : stageParam === 'production' ? 'master' : 'staging'
```suggestion
  distributionParam || stageParam === 'production' ? 'master' : 'staging'
```

2021-07-08 13:35 UTC, merged

2021-07-08 15:37 UTC, arianvp commented
Thanks for merging ! I'll make sure everything is good once you push the new staging build and will report back if I still run into weird things.