chore: Set permissions for GitHub actions
wireapp/wire-webapp pull request #12916
Opened 2022-04-25 23:31 UTC by naveensrinivasan

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

2022-04-25 23:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=12916) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=12916) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-webapp?pullRequest=12916) it.</sub>

2022-04-26 08:24 UTC, atomrc requested changes
Thanks a lot @naveensrinivasan for your valuable contribution :pray: 

There is a slight error in our linting job. Applying the suggested change should fix it. 

Thanks again

2022-04-26 08:24 UTC, atomrc commented on .github/workflows/codeql-analysis.yml
> +      security-events: write  # for github/codeql-action/analyze to upload SARIF results
```suggestion
      actions: read # for github/codeql-action/init to get workflow details
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/analyze to upload SARIF results
```

For some reason, the double space before the comment break the linting job. Not sure why, we should fix that on our end, but for the moment, would you mind applying those change. Thanks

2022-04-26 10:19 UTC, naveensrinivasan commented
> Thanks a lot @naveensrinivasan for your valuable contribution 🙏
> 
> There is a slight error in our linting job. Applying the suggested change should fix it.
> 
> Thanks again

Took care of it. Thanks

2022-04-26 10:29 UTC, merged

2022-04-26 10:29 UTC, atomrc commented
Merged :+1: 
Thanks @naveensrinivasan