fix: participant details do not update (ACC-107)
wireapp/wire-webapp pull request #12980
Opened 2022-05-06 07:22 UTC by przemvs

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-05-06 10:33 UTC, tlebon commented on src/script/components/panel/UserActions.tsx
> +  useKoSubscribableChildren(user, [
feels like destructuring this and/or not passing in the user prop *to the component* would be more appropriate based on other patterns we are using.

2022-05-06 10:35 UTC, tlebon commented on src/script/components/panel/UserActions.tsx
> +  useKoSubscribableChildren(user, [
![Screenshot 2022-05-06 at 12 35 04](https://user-images.githubusercontent.com/37285713/167115939-c6a98575-4a9a-4511-88bc-ad91f4c57e04.png)

2022-05-06 10:59 UTC, przemvs commented on src/script/components/panel/UserActions.tsx
> +  useKoSubscribableChildren(user, [
Sure, i saw in different component usage without passing it to variable, so i can make this hook as variable and use in further functionality.

2022-05-06 12:14 UTC, tlebon commented on src/script/components/panel/UserActions.tsx
> +  useKoSubscribableChildren(user, [
maybe we should wait for @atomrc to weigh in on this also, but it seems like using the hook only is the correct action in this case.

2022-05-09 09:04 UTC, thisisamir98 commented on src/script/components/panel/UserActions.tsx
> +  useKoSubscribableChildren(user, [
@przemvs you should destruct the variables you need and use them in the component, example:
ConnectedMessage.tsx

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/63250054/167377454-03b3c1eb-3885-4636-8d6b-399596b60cc5.png">

2022-05-09 09:50 UTC, atomrc commented on src/script/components/panel/UserActions.tsx
> +  useKoSubscribableChildren(user, [
@przemvs we might have a few places where the hook is used without reading the returned values, but this is mostly hacks/dirty fixes. We should really consume the returned values in the render.

In this case, that would mean replacing all occurrences of `user.<property>()` with the desctructured property from the hook

2022-05-09 10:26 UTC, przemvs commented on src/script/components/panel/UserActions.tsx
> +  useKoSubscribableChildren(user, [
@atomrc  @tlebon @thisisamir98 fixed :)

2022-05-09 10:29 UTC, atomrc approved these changes
Great man. Awesome that you discovered the use of the `useKoSubscribableChildren`. 
Great job :+1:

2022-05-09 10:30 UTC, atomrc requested changes

2022-05-09 10:30 UTC, atomrc commented on src/script/components/panel/UserActions.tsx
> +  // isUnknown: false
Oh can we remove those comments

2022-05-09 10:36 UTC, atomrc commented on src/script/components/panel/UserActions.tsx
> +  // isUnknown: false
```suggestion
```

2022-05-09 10:37 UTC, atomrc approved these changes

2022-05-09 10:38 UTC, tlebon approved these changes

2022-05-09 10:39 UTC, thisisamir98 approved these changes

2022-05-10 08:26 UTC, merged