fix: replace avselect with UI toolkit acc-79
wireapp/wire-webapp pull request #13157
Opened 2022-06-08 09:11 UTC by V-Gira

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

The select component in the Preference Tab does not conform to accessibility standards

>Dropdown fields don’t have any visible states and the option selection list is not styled according to the designs

![image](https://user-images.githubusercontent.com/78490891/172578690-33a0e555-f723-44d2-8d79-059b19a836de.png)

### Solutions

Make use of the component in the the ltest version of the UI kit

![image](https://user-images.githubusercontent.com/78490891/172578185-95ef0afd-6870-46a8-b77a-489dee703fbe.png)

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-06-08 09:18 UTC, przemvs requested changes
If you need a help, ask me :)

2022-06-08 09:18 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +          options={devices.map(({deviceId, label}) => ({label: label || defaultDeviceName, value: deviceId}))}
Please move devices.map() to variable :)

2022-06-08 09:18 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +          value={device}
And if you map this device you can get currentValue from options, using .find method, so you don't need to use useState :)

2022-06-08 09:18 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +          }}
And here you need only pass onChange={onChange}

2022-06-08 09:18 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +  const [device, setDevice] = useState({label: currentDevice.label, value: value});
This variables are necessary. You have value and devices from props. So you need to map devices to { label, value }. And then you can manipulate to find currentDevice from mapped list using find method :)

2022-06-08 09:20 UTC, thisisamir98 commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +        />
```suggestion
          onChange={(selectedDeviceId: string) => {
            const selectedDevice = devices.find(device => device.deviceId === selectedDeviceId);
            setDevice({label: selectedDevice.label, value: selectedDeviceId});
            onChange(selectedDeviceId);
          }}
          dataUieName={uieName}
          options={devices.map(({deviceId, label}) => ({label: label || defaultDeviceName, value: deviceId}))}
          value={device}
          label={title}
          disabled={disabled}
        />
```

2022-06-08 09:21 UTC, thisisamir98 commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +          onChange={(selectedDevice: string) => {
also I think it's better to extract this to a separate function, maybe `onSelectNewDevice`

2022-06-08 10:06 UTC, V-Gira commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +          options={devices.map(({deviceId, label}) => ({label: label || defaultDeviceName, value: deviceId}))}
I went with getOptionsFromDevices, it's a bit chunky

2022-06-08 11:30 UTC, przemvs requested changes
Few changes :)

You don't need to map currentOption, you should get this value from options.

2022-06-08 11:30 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +  }));
```suggestion
  const devicesList = devices.map(({deviceId, label}) => ({
    label: label || defaultDeviceName,
    value: deviceId,
  }));
  const currentValue = devicesList.find(device => device.value === value)
```

2022-06-08 11:30 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +          value={currentOption}
```suggestion
          options={devicesList}
          value={currentValue}
```

2022-06-08 11:30 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
>    return (
```suggestion
  const disabled = lessThanTwoDevices || isRequesting;
  
  return (
```

2022-06-08 11:30 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/avPreferences/DeviceSelect.tsx
> +      >
```suggestion
      <div css={{width: '550px'}}>
```

2022-06-13 15:19 UTC, atomrc approved these changes
This looks solid!!! Awesome work man :sunglasses: :rocket:

2022-06-14 06:08 UTC, przemvs reviewed
Few comments :)

2022-06-14 07:57 UTC, przemvs requested changes
Few comments :)

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/LoginForm.tsx
> +      <Input
Pass id for input, can be the same like name :)

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/LoginForm.tsx
> +      {isFetching ? (
```suggestion
      />
      
      {isFetching ? (
```
Add spacing between lines

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +  );
Please move mapper for COUNTRY_CODES to variable above countryList, eg 'additionalCountriesList'. And then spread additionalContriesList instead of Array.concat() :)

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +        id=""
Please pass proper id, eg. 'select-phone'.

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +        dataUieName=""
Also here please pass e.g. 'select-phone'.

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +        value={{label: country, value: countryCode}}
You need to get value from countryList using find method :)

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +      <InputBlock>
```suggestion
      />
      
      <InputBlock>
```
Spacing here

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +          <Input
Input needs id for proper work with label, pass the same id like a data-uie-name

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +              setCountry(codeNumbers ? getCountryByCode(codeNumbers) || 'X1' : 'X0');
Hmm.. This statement isn't readable. If codeNumbers is false you wanna pass 'X1' or 'X0' ?  You miss ().

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +          <Input
Pass id for Input, can be the same like as name.

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +          {isFetching ? (
```suggestion
          />
          
          {isFetching ? (
```

Spacing here

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/page/SingleSignOnForm.tsx
> +          <Input
Pass id for input, same as name ;)

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/page/SingleSignOnForm.tsx
> +              Config.getConfig().FEATURE.ENABLE_DOMAIN_DISCOVERY
Move Config.getConfig() to variable above return, and then use eg, config.FEATURE....

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/page/SingleSignOnForm.tsx
> +              Config.getConfig().FEATURE.ENABLE_DOMAIN_DISCOVERY
Same there, use Config.getConfig() as variable.

2022-06-14 07:57 UTC, przemvs commented on src/script/auth/page/SingleSignOnForm.tsx
> +              Config.getConfig().FEATURE.ENABLE_DOMAIN_DISCOVERY
Use Config.getConfig() as variable.

2022-06-14 07:57 UTC, przemvs commented on src/script/page/MainContent/MainContent.tsx
> +    };
Move this above useEffect, you don't need this function here. Also you cannot pass theme, because you're using upper. So you can have problems. Or rename `const theme` on line 60, to `currentTheme`

2022-06-14 09:03 UTC, V-Gira commented on src/script/auth/component/PhoneLoginForm.tsx
> +              setCountry(codeNumbers ? getCountryByCode(codeNumbers) || 'X1' : 'X0');
Haha I agree, it's from the original code, I plead non-guilty.

2022-06-14 09:28 UTC, V-Gira commented on src/script/auth/component/PhoneLoginForm.tsx
> +              setCountry(codeNumbers ? getCountryByCode(codeNumbers) || 'X1' : 'X0');
I can't parse it but it does work, it sets the select to "country code" if the input is empty and "invalid country code" when the input doesn't match a country code

2022-06-14 10:15 UTC, przemvs approved these changes
Few changes and you can merge! :)

2022-06-14 10:15 UTC, przemvs commented on src/script/auth/component/PhoneLoginForm.tsx
> +    ...countryList,
Move this to the end, because we wanna have X0, X1 on beginning :)

2022-06-14 10:15 UTC, przemvs commented on src/script/auth/page/SingleSignOnForm.tsx
> +              enableDomainDiscovery ? ValidationError.FIELD.SSO_EMAIL_CODE.name : ValidationError.FIELD.SSO_CODE.name
Move values to variable and pass to this attributes :)

2022-06-14 10:46 UTC, przemvs approved these changes

2022-06-14 11:04 UTC, merged