fix: messages bigger than viewport not being read (#SQSERVICES-1558)
wireapp/wire-webapp pull request #13338
Opened 2022-07-13 10:18 UTC by PatrykBuniX

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

There is a bug where messages bigger than window's viewport are not being read. 

### Causes

Using `IntersectionObserver` we mark the messages as read when the whole message is visible in the viewport, so it does not work for messages higher that viewport. 

### Solutions

I suggest adding `allowBiggerThanViewport` boolean (optional, defaults to `false`) to the `<InViewport />` component's props. When its value is set to true, and observed element is higher than viewport, we treat this element as visible.

When element will be considered as visible:

`const isVisible = isIntersecting && (!fullyInView || isFullyInView() || isBiggerThanRoot());`

`isIntersecting`: The element must be partially visible (at least 1%), and:
- `!fullyInView` (`<InViewport />`'s prop) - we don't want the whole element to be visible, or
-  `isFullyInView()` - we want the whole element to be visible and it's fully in the view (doesn't work for higher messages)

after this PR is merged:

- `isBiggerThanRoot()` - we want the whole element to be visible, but we also allow it to be partially visible when it's bigger than viewport (only if `allowBiggerThanViewport` is set to `true`) 

This is how I check if element is bigger than viewport:
```ts
const isBiggerThanRoot = () => {
      return (
        allowBiggerThanViewport &&
        !!rootBounds &&
        (element.clientHeight > rootBounds.height || element.clientWidth > rootBounds.width)
      );
};
```

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-07-13 10:30 UTC, przemvs requested changes

2022-07-13 10:30 UTC, przemvs commented on src/script/components/MessagesList/Message/index.tsx
> +  const wrappedContent = props.onVisible ? (
Please spread onVisible property.

2022-07-13 10:30 UTC, przemvs commented on src/script/components/MessagesList/Message/index.tsx
> +    <InViewport allowBiggerThanViewport onVisible={props.onVisible}>
Please spread onVisible property.

2022-07-13 10:30 UTC, przemvs commented on src/script/components/utils/InViewport.tsx
> +  allowBiggerThanViewport?: boolean;
Move non optional props to top of interface

2022-07-13 10:30 UTC, przemvs commented on src/script/components/utils/InViewport.tsx
> +      allowBiggerThanViewport,
I think it should be passed as useEffect dependency ?

2022-07-13 10:30 UTC, przemvs commented on src/script/ui/viewportObserver.ts
> +    const isBiggerThanRoot = () => {
I think you can memoize this function :)

2022-07-13 10:30 UTC, przemvs commented on src/script/ui/viewportObserver.ts
> +    const isVisible = isIntersecting && (!fullyInView || isFullyInView() || isBiggerThanRoot());
!fullyInView || isFullyInView() - hmm.. this naming of **isFullyInView** and **fullyInView** looks name the same :D Maybe rename **isFullyInView** to **checkIsFullyInView** ? And then move `(!fullyInView || checkIsFullyInView())` to variable isFullyInView ?

2022-07-13 10:30 UTC, przemvs commented on src/script/ui/viewportObserver.ts
> +const trackElement = (
Hmm.. I think the fullyInView, allowBiggerThanViewport can be optional, and have default value as false :)

2022-07-13 10:43 UTC, PatrykBuniX commented on src/script/ui/viewportObserver.ts
> +    const isBiggerThanRoot = () => {
Its just a regular function, not a hook or component, can't use `useMemo` in this case (rules of hooks).

2022-07-13 10:51 UTC, PatrykBuniX commented on src/script/ui/viewportObserver.ts
> +    const isVisible = isIntersecting && (!fullyInView || isFullyInView() || isBiggerThanRoot());
I don't want to group these two into a variable, they are two separate conditions, I'll change `fullyInView` name to `requireFullyInView` though to make it more obvious what it's for :D .

2022-07-13 10:56 UTC, przemvs commented on src/script/ui/viewportObserver.ts
> +    const isBiggerThanRoot = () => {
Ahh.. i doesn't look at that. Sorry :D

2022-07-13 11:42 UTC, tlebon commented on src/script/components/utils/InViewport.tsx
> +  allowBiggerThanViewport?: boolean;
maybe we can turn on a lint rule for this also

2022-07-13 11:44 UTC, przemvs approved these changes
Code LGTM, 1 thing :)

2022-07-13 11:44 UTC, przemvs commented on src/script/ui/viewportObserver.ts
> +  container?: HTMLElement,
Maybe move container above requireFullyInView and then in src/script/view_model/bindings/CommonBindings.ts you can pass to trackElement
```
viewportObserver.trackElement(
      element,
      (isInViewport: boolean) => {
        inViewport = isInViewport;
        triggerCallbackIfVisible();
      },
      container,
      true,
    );
```

What do you think? :)

2022-07-13 11:44 UTC, przemvs commented on src/script/components/utils/InViewport.tsx
> +  allowBiggerThanViewport?: boolean;
Yeah, it will be the best!

2022-07-13 11:47 UTC, PatrykBuniX commented on src/script/ui/viewportObserver.ts
> +  container?: HTMLElement,
seems cool, so the boolean modifiers are always at the last place 👍

2022-07-13 15:05 UTC, tlebon approved these changes

2022-07-13 15:06 UTC, merged

2022-09-22 16:13 UTC, atomrc commented
Should also address https://github.com/wireapp/wire-desktop/issues/5961