runfix: address broken inputs when removing devices acc-210
wireapp/wire-webapp pull request #13341
Opened 2022-07-14 12:57 UTC by V-Gira

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/ACC-210" title="ACC-210" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />ACC-210</a>  [web] Usability of deleting a device on login (when device limit is reached) can be improved
  </td></table>
  <br />
 

----

# What's new in this PR?

### Issues

- Inputs in the remove device screen are way too narrow
![3306c1a8-46b6-4250-b961-df51e37a355d](https://user-images.githubusercontent.com/78490891/178987147-fe3a7bb1-5094-42e6-b410-15edfd8ae88f.png)

### Solutions

- adjust style according to [new mockup](https://www.figma.com/file/OrP9jAJdfttfvsm3nxnihP/Accessibility-Quick-Wins-(Web%2FDesktop)?node-id=2711%3A17289)
- (Changes to inputs border radius need to be adressed in the ui-kit)

![image](https://user-images.githubusercontent.com/78490891/179210229-3653e349-a3bf-41ae-8766-07cc9cbb5035.png)

2022-07-14 13:06 UTC, PatrykBuniX approved these changes

2022-07-15 11:24 UTC, PatrykBuniX approved these changes

2022-07-15 11:34 UTC, przemvs requested changes
LGTM, 1 change :D

2022-07-15 11:34 UTC, przemvs commented on src/script/auth/component/ClientItem.tsx
> +  const height = animationPosition * 70;
What's 70 mean? Move this to variable, also please move another magic numbers :D

2022-07-15 12:37 UTC, V-Gira commented on src/script/auth/component/ClientItem.tsx
> +  const height = animationPosition * 70;
Dammit, someone noticed! I'll have to clean up that mess :face_with_spiral_eyes:  I'll move all the paddings, margins, etc to variables. I plead non guilty though

2022-07-15 14:13 UTC, arjita-mitra commented on src/script/auth/component/ClientItem.tsx
> +          backgroundColor: selected ? '#FFF' : '',
can you use @white instead? its in color.less

2022-07-15 14:18 UTC, V-Gira commented on src/script/auth/component/ClientItem.tsx
> +          backgroundColor: selected ? '#FFF' : '',
Don't have access to those css variables here I'm afraid :(

2022-07-18 06:32 UTC, przemvs requested changes
1 thing left :)

2022-07-18 06:32 UTC, przemvs commented on src/script/auth/component/ClientItem.tsx
> +  const spacing = {
It's bad name for variable. Please change it for what it mean e.g inputSpacing, sthSpacing.

2022-07-18 07:50 UTC, V-Gira commented on src/script/auth/component/ClientItem.tsx
> +  const spacing = {
```suggestion
  const animatedCardSpacing = {
```

2022-07-19 08:20 UTC, przemvs approved these changes

2022-07-19 08:22 UTC, merged