feat: search visibility (#SQSERVICES-1442)
wireapp/wire-webapp pull request #13402
Opened 2022-07-29 16:01 UTC by PatrykBuniX

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Search visibility feature:
- feature's `status`/`config` change notification on app's load
- current feature's config state modal opens on info button click  

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-08-01 11:40 UTC, tlebon commented on src/script/team/TeamRepository.ts
> +import {ROLE, ROLE as TEAM_ROLE, roleFromTeamPermissions} from '../user/UserPermission';
we have two separate exports called ROLE? that seems bad

2022-08-01 11:48 UTC, przemvs requested changes

2022-08-01 11:48 UTC, przemvs commented on src/script/components/UserSearchInputInfoButton.tsx
> +import {FeatureList} from '@wireapp/api-client/src/team';
Please sort imports, 1st - external, 2nd - components/utils, 3rd - rest. And add spacing between imports :)

2022-08-01 11:48 UTC, przemvs commented on src/script/team/TeamRepository.ts
> +    //inbound
I think this comment is necessary

2022-08-01 11:48 UTC, przemvs commented on src/script/team/TeamRepository.ts
> +      searchVisibilityInbound: hasSearchVisibilityInboundChanged ? newConfig.searchVisibilityInbound : undefined,
```suggestion
      ...(hasSearchVisibilityInboundChanged && { searchVisibilityInbound: newConfig.searchVisibilityInbound }),
```

2022-08-01 11:48 UTC, przemvs commented on src/script/team/TeamRepository.ts
> +      searchVisibilityOutbound: hasSearchVisibilityOutboundChanged ? newConfig.searchVisibilityOutbound : undefined,
```suggestion
      ...(hasSearchVisibilityOutboundChanged && { searchVisibilityOutbound: newConfig.searchVisibilityOutbound }),
```

2022-08-01 11:48 UTC, przemvs commented on src/script/team/TeamSearchVisibilitySetting.ts
> +import {WebAppEvents} from '@wireapp/webapp-events';
Please sort imports.

2022-08-01 13:25 UTC, przemvs approved these changes

2023-05-10 07:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=13402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=13402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-webapp?pullRequest=13402) it.</sub>

2025-01-03 17:01 UTC, closed without merging