refactor: migrate detail-view to React (#ACC-239)
wireapp/wire-webapp pull request #13426
Opened 2022-08-02 14:05 UTC by przemvs

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/ACC-239" title="ACC-239" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />ACC-239</a>  [Web] Migrate detail-view component to React
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-08-03 12:29 UTC, aweiss-dev requested changes

2022-08-03 12:29 UTC, aweiss-dev commented on src/script/components/Modals/DetailViewModal/DetailViewModalFooter.tsx
> +}) => {
Not a fan of using FC.
To be future-proof, I would recommend just typing the props and getting rid of FC.

2022-08-03 12:29 UTC, aweiss-dev commented on src/script/components/Modals/DetailViewModal/DetailViewModalHeader.tsx
> +const DetailViewModalHeader: FC<DetailViewModalHeaderProps> = ({messageEntity, onCloseClick}) => {
FC

2022-08-03 12:29 UTC, aweiss-dev commented on src/script/components/Modals/DetailViewModal/index.tsx
> +const DetailViewModal: FC<DetailViewModalProps> = ({
FC

2022-08-03 12:29 UTC, aweiss-dev commented on src/script/page/MainContent/panels/Collection/Collection.test.tsx
> +  } as Partial<ConversationRepository>;
const mockConversationRepository: Partial<ConversationRepository> = {}
 
 would be the preferable way of typing here.

2022-08-03 12:29 UTC, aweiss-dev commented on src/script/page/MainContent/panels/Collection/CollectionDetails.tsx
> +const CollectionDetails: React.FC<CollectionDetailsProps> = ({
FC

2022-08-03 12:29 UTC, aweiss-dev commented on src/script/page/MainContent/panels/Collection/CollectionItem.tsx
> +const CollectionItem: FC<CollectionItemProps> = ({message, onImageClick}) => {
FC

2022-08-03 12:29 UTC, aweiss-dev commented on src/script/view_model/content/MessageListViewModel.ts
> +      currentMessageEntity: messageEntity as ContentMessage,
Is this as really needed or could it be resolved by stronger typing?

I really don't like the forced deactivation of the ts compiler. I stumbled on a lot of problems already caused by type assertions.

2022-08-03 12:29 UTC, aweiss-dev commented on src/script/components/Modals/DetailViewModal/index.tsx
> +    setItems(messageEntities as ContentMessage[]);
Better to use a typeguard

2022-08-03 13:37 UTC, przemvs commented on src/script/components/Modals/DetailViewModal/DetailViewModalFooter.tsx
> +}) => {
You mean:
({
```suggestion
const DetailViewModalFooter: FC<DetailViewModalFooterProps> = ({
  messageEntity,
  conversationEntity,
  onLikeClick,
  onReplyClick,
  onDownloadClick,
}: {
messageEntity: MessageEntity,
...rest
})) => {
```

or 

```suggestion
const DetailViewModalFooter = ({
  messageEntity,
  conversationEntity,
  onLikeClick,
  onReplyClick,
  onDownloadClick,
}): DetailViewModalFooterProps => {
```

2022-08-03 13:38 UTC, przemvs commented on src/script/components/Modals/DetailViewModal/DetailViewModalFooter.tsx
> +}) => {
And why you recommend to not use FC ?

2022-08-08 13:01 UTC, przemvs commented on src/script/page/MainContent/panels/Collection/Collection.test.tsx
> +  } as Partial<ConversationRepository>;
done.

2022-08-08 13:55 UTC, przemvs commented on src/script/view_model/content/MessageListViewModel.ts
> +      currentMessageEntity: messageEntity as ContentMessage,
done.

2022-08-08 13:55 UTC, przemvs commented on src/script/components/Modals/DetailViewModal/index.tsx
> +    setItems(messageEntities as ContentMessage[]);
done.

2022-08-24 07:39 UTC, PatrykBuniX commented on src/script/components/Modals/DetailViewModal/DetailViewModalFooter.tsx
> +      {messageEntity.isReactable() && !isRemovedFromConversation && (
can't it be destructured from `useKoSubscribableChildren` (line 44)?

2022-08-24 07:39 UTC, PatrykBuniX commented on src/script/components/Modals/DetailViewModal/DetailViewModalFooter.tsx
> +      {messageEntity.isReplyable() && !isRemovedFromConversation && (
can't it be destructured from useKoSubscribableChildren (line 44)?

2022-08-24 07:39 UTC, PatrykBuniX commented on src/script/components/Modals/DetailViewModal/DetailViewModalFooter.tsx
> +      {messageEntity.isDownloadable() && (
can't it be destructured from useKoSubscribableChildren (line 44)?

2022-08-24 07:39 UTC, PatrykBuniX commented on src/script/components/Modals/DetailViewModal/DetailViewModalHeader.tsx
> +          {messageEntity.unsafeSenderName()}
get `unsafeSenderName` from `useKoSubscribableChildren`

2022-08-24 07:39 UTC, PatrykBuniX commented on src/script/guards/Message.ts
> +export const isDraftMessageWithReplyId = (message: Draft): message is Draft => 'messageId' in message.reply;
explicit return type doesn't make sense here imo: you already require to pass `Draft` type, so it's always `Draft`, you are just checking if it has messageId field. I would just remove the return type here 🤔

2022-08-24 07:40 UTC, aweiss-dev approved these changes

2022-08-24 07:46 UTC, przemvs commented on src/script/components/Modals/DetailViewModal/DetailViewModalFooter.tsx
> +      {messageEntity.isReactable() && !isRemovedFromConversation && (
### 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/13432884/186361104-b29e601b-5eeb-446a-a321-67405b5e69e5.png">

2022-08-24 07:46 UTC, przemvs commented on src/script/components/Modals/DetailViewModal/DetailViewModalFooter.tsx
> +      {messageEntity.isReplyable() && !isRemovedFromConversation && (
Same like as isReactable.

2022-08-24 07:48 UTC, przemvs commented on src/script/components/Modals/DetailViewModal/DetailViewModalFooter.tsx
> +      {messageEntity.isDownloadable() && (
Same like as isReactable.

2022-08-24 07:57 UTC, przemvs commented on src/script/guards/Message.ts
> +export const isDraftMessageWithReplyId = (message: Draft): message is Draft => 'messageId' in message.reply;
done.

2022-08-24 07:57 UTC, przemvs commented on src/script/components/Modals/DetailViewModal/DetailViewModalHeader.tsx
> +          {messageEntity.unsafeSenderName()}
done.

2022-08-24 08:11 UTC, PatrykBuniX approved these changes

2022-08-24 10:59 UTC, V-Gira approved these changes

2022-08-30 07:53 UTC, PatrykBuniX approved these changes

2022-08-30 08:01 UTC, merged