runfix: address changes to call UI camera switcher acc-81
wireapp/wire-webapp pull request #13502
Opened 2022-08-19 11:48 UTC by V-Gira

----
### Issues

- The camera switcher pagination was not addressed during the call-ui changes
- The user pagination's size was not correct
- Avatars are available to keyboard navigation in the call-ui

### Solutions

- Address the pagination changes
- Expand the height of the call-ui to accomodate the camera-switcher
- Move the tab index from the avatar component to the chat window index.tsx

![Screenshot from 2022-08-19 13-47-52](https://user-images.githubusercontent.com/78490891/185612029-94ad7420-ecdd-43cc-a6dc-cdca4df8a266.png)
![Screenshot from 2022-08-19 13-48-11](https://user-images.githubusercontent.com/78490891/185612038-a00676e4-1770-49fa-b4c1-20dc9ec3f042.png)

2022-08-19 11:51 UTC, przemvs requested changes

2022-08-19 11:51 UTC, przemvs commented on src/script/components/calling/DeviceToggleButton.tsx
> +              backgroundColor: device === currentDevice ? 'var(--accent-color)' : 'var(--app-bg-secondary)',
Move device === currentDevice to variable, and pass it in other places :)

2022-08-19 12:49 UTC, thisisamir98 approved these changes

2022-08-22 07:56 UTC, przemvs approved these changes
LGTM, please check 1 thing.

2022-08-22 07:56 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/index.tsx
> +          participant={message.user()}
Hmm.. I think this should come from useKoSubscribableChildren. Please check it.

2022-08-22 07:58 UTC, merged