chore: Fix Message components type errors
wireapp/wire-webapp pull request #13551
Opened 2022-08-27 17:30 UTC by atomrc

This will fix typescript error around the Message rendering components (mesages and assets)

Bring the total number of strict type errors from 2062 to 2039

2022-09-05 07:38 UTC, przemvs requested changes
Few changes :)

2022-09-05 07:38 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/MessageQuote.tsx
> +  const [textQuoteElement, setTextQuoteElement] = useEffectRef<HTMLDivElement>();
Maybe move to useRef instead of useEffectRef ;)

2022-09-05 07:38 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +            onPointerLeave={() => startTimeout()}
```suggestion
            onPointerLeave={startTimeout}
```

2022-09-05 07:38 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +              }
Move this to function, you have duplicated it :)

2022-09-05 07:38 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +                visibility: transferState === AssetTransferState.UPLOADING ? 'hidden' : undefined,
Do smth like that :)
```suggestion
                {...(transferState === AssetTransferState.UPLOADING && { visibility: 'hidden'}),
```

2022-09-05 07:38 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +                visibility: transferState === AssetTransferState.UPLOADING ? 'hidden' : undefined,
Also maybe move this transferState === AssetTransferState.UPLOADING to variable, you have used it multiple times :)

2022-09-05 07:38 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/index.tsx
> +      const assetId = asset.id;
Maybe use this variable above if statement :) You can use it also in this if variable :)

2022-09-05 07:38 UTC, przemvs commented on src/script/ui/viewportObserver.ts
> +      return () => {};
Only return doesn't work ? :)

2022-09-05 07:38 UTC, przemvs commented on src/script/ui/viewportObserver.ts
> +export const useViewPortObserver = (elementRef?: HTMLElement, defaultIsVisible: boolean = false): boolean => {
Hmm.. defaultIsVisible shouldn't be ?: boolean ? 🤔

2022-09-05 07:38 UTC, thisisamir98 approved these changes

2022-09-05 07:43 UTC, atomrc commented on src/script/components/MessagesList/Message/ContentMessage/MessageQuote.tsx
> +  const [textQuoteElement, setTextQuoteElement] = useEffectRef<HTMLDivElement>();
We need effect ref in this case, since we are listening to the object change and trigger an effect when it changes.

2022-09-05 07:44 UTC, atomrc commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +              }
True that, good call 👍

2022-09-05 07:51 UTC, atomrc commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +                visibility: transferState === AssetTransferState.UPLOADING ? 'hidden' : undefined,
What is the benefit of this method, I don't see any benefit, I personally find it harder to read 🤔

2022-09-05 07:53 UTC, atomrc commented on src/script/ui/viewportObserver.ts
> +export const useViewPortObserver = (elementRef?: HTMLElement, defaultIsVisible: boolean = false): boolean => {
It has a default value, so the `?` is not needed

2022-09-05 07:53 UTC, atomrc commented on src/script/ui/viewportObserver.ts
> +      return () => {};
Doesn't typecheck (cause the function has mixed return types then I guess). Let me try to see what I can do

2022-09-05 07:56 UTC, atomrc commented on src/script/ui/viewportObserver.ts
> +      return () => {};
actually it does typecheck, good call, thanks :)

2022-09-05 08:26 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +                visibility: transferState === AssetTransferState.UPLOADING ? 'hidden' : undefined,
If you use it you don't need to pass undefined, and for me it's better than passing undefined :)

2022-09-05 08:56 UTC, atomrc commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +                visibility: transferState === AssetTransferState.UPLOADING ? 'hidden' : undefined,
Fixed with `className` :)

2022-09-05 15:39 UTC, PatrykBuniX approved these changes

2022-09-05 20:32 UTC, przemvs requested changes
Few more comments :)

2022-09-05 20:32 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +  const syncVideoTimeRest = () => videoElement && setVideoTimeRest(videoElement.duration - videoElement.currentTime);
Please make if condition. It will be more readable.

2022-09-05 20:32 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +              className={clx({hidden: transferState === AssetTransferState.UPLOADING})}
Move transferState === AssetTransferState.UPLOADING to variable, you using this multiple times.

2022-09-05 20:32 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +                            transferState === AssetTransferState.UPLOADING ? cancelUpload() : asset.cancelDownload()
Move transferState === AssetTransferState.UPLOADING to variable, you using this multiple times.

2022-09-05 20:32 UTC, przemvs commented on src/script/components/MessagesList/Message/index.tsx
> +      props.scrollTo?.({center: true, element: messageElementRef.current});
Why not to spread scrollTo property ? In this component you have spreaded different props.

2022-09-05 20:32 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +                        />
Maybe prepare commonProps for this both MediaButtons ? Or you can use only one compontn <MediaButton /> by passing large={!displaySmall} ?

2022-09-06 06:57 UTC, atomrc commented on src/script/components/MessagesList/Message/index.tsx
> +      props.scrollTo?.({center: true, element: messageElementRef.current});
fair point :)

2022-09-06 07:02 UTC, atomrc commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +                            transferState === AssetTransferState.UPLOADING ? cancelUpload() : asset.cancelDownload()
oh and I realized that the `useAssetTransfer` hook already contains those variables, good catch ;)

2022-09-06 07:12 UTC, atomrc commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +                        />
makes sense, actually I can only switch the `large` property true/false and it works as expected, no need for this condition at all, good catch

2022-09-06 07:13 UTC, atomrc commented on src/script/components/MessagesList/Message/ContentMessage/asset/VideoAsset.tsx
> +  const syncVideoTimeRest = () => videoElement && setVideoTimeRest(videoElement.duration - videoElement.currentTime);
done

2022-09-06 07:16 UTC, przemvs approved these changes
LGTM! :)

2022-09-06 07:48 UTC, merged