refactor: Migrate ConversationDetails component to React (#ACC-258)
wireapp/wire-webapp pull request #13602
Opened 2022-09-05 11:38 UTC by przemvs

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/ACC-258" title="ACC-258" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />ACC-258</a>  [Web] Migrate ConversationDetails component to React
  </td></table>
  <br />
 

TODO: Need to update tests

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-09-05 13:03 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailsBottomActions.tsx
> +            data-bind="click: clickOnNotifications"
This should be converted to a React `onClick`

2022-09-05 13:20 UTC, atomrc requested changes

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailsBottomActions.tsx
> +            data-bind="click: clickOnNotifications"
This should be converted to a React `onClick`

2022-09-05 13:20 UTC, atomrc commented on src/script/conversation/ConversationRepository.ts
> +  public getConversationState(): ConversationState {
Let's use `container.resolve(ConversationState)` inside the component instead. This will be easier to get rid of the Repositories and move to a state manager later on

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailsHeader.tsx
> +  }, [textAreaRef, isEditingName, groupName]);
```suggestion
  }, [isEditingName, groupName]);
```

Ref cannot be put to dependencies, they won't trigger an effect. If you need an effect triggering with the ref change, you need to use `useEffectRef`

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailsHeader.tsx
> +  // TODO: Update height of textarea on change
hummm, I think this really needs to be done

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailsOptions.tsx
> +  const onServiceOptionsClick = () => togglePanel(PanelViewModel.STATE.SERVICES_OPTIONS, {entity: activeConversation});
Let's name those with the action they are doing, not the time at which they are triggered:

```suggestion
  const openNotificationsPanel = () => togglePanel(PanelViewModel.STATE.NOTIFICATIONS, {entity: activeConversation});

  const openTimedMessagePanel = () => togglePanel(PanelViewModel.STATE.TIMED_MESSAGES, {entity: activeConversation});

  const openOptionsPanel = () => togglePanel(PanelViewModel.STATE.GUEST_OPTIONS, {entity: activeConversation});

  const openServicePanel = () => togglePanel(PanelViewModel.STATE.SERVICES_OPTIONS, {entity: activeConversation});
```

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailstest.temp
> +/*
If you have constraint and need to work on something else, please create a PR already with this failing test but do not add it to this PR, there is a risk that this file stays like this forever and no one will ever go back to it.

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const firstParticipant = activeConversation.firstUserEntity();
This needs to be added to the `useKoSub` call above since it's an observable it can change over time

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const onDevicesClick = () =>
```suggestion
  const openParticipantDevices = () =>
```

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const onAddParticipants = () =>
```suggestion
  const openAddParticipants = () =>
```

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const onShowUserClick = (userEntity: User) =>
```suggestion
  const showUser = (userEntity: User) =>
```

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const onShowService = (serviceEntity: ServiceEntity) =>
```suggestion
  const showService = (serviceEntity: ServiceEntity) =>
```

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const onShowAllClick = () =>
```suggestion
  const showAllParticipants = () =>
```

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  };
We could extract that function to an external file (right next to the component) and have a few unit tests for it

2022-09-05 13:20 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const clickToToggleMute = () => actionsViewModel.toggleMuteConversation(activeConversation);
```suggestion
  const toggleMute = () => actionsViewModel.toggleMuteConversation(activeConversation);
```

2022-09-05 21:10 UTC, przemvs commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailsBottomActions.tsx
> +            data-bind="click: clickOnNotifications"
Ahh... i missed it :'(

2022-09-06 05:41 UTC, przemvs commented on src/script/conversation/ConversationRepository.ts
> +  public getConversationState(): ConversationState {
Thanks! i'm looking how to get it without preparing getter/setter :)

2022-09-06 05:42 UTC, przemvs commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailsHeader.tsx
> +  }, [textAreaRef, isEditingName, groupName]);
useEffectRef not needed ;)

2022-09-06 05:42 UTC, przemvs commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailsHeader.tsx
> +  // TODO: Update height of textarea on change
fixed

2022-09-06 05:42 UTC, przemvs commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetailstest.temp
> +/*
sure!

2022-09-06 07:36 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +                        // arrow
What does that mean?

2022-09-06 07:42 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +import getConversationActions from './components/getConversationActions';
Let's maybe move it to a `util` folder, rather than in `components`. 

`page/RightSidebar/utils/getConversationActions`

2022-09-06 07:46 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const panelContentRef = useRef<HTMLDivElement>(null);
you will need a `useEffectRef` here, cause we need a rerender when the ref is updated (ref do not trigger a re-render on their own)

2022-09-06 07:47 UTC, atomrc requested changes

2022-09-06 07:47 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const panelContentRef = useRef<HTMLDivElement>(null);
you will need a `useEffectRef` here, cause we need a rerender when the ref is updated (ref do not trigger a re-render on their own)

2022-09-06 09:22 UTC, przemvs commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const panelContentRef = useRef<HTMLDivElement>(null);
It works without useEffectRef ;)

2022-09-06 09:23 UTC, przemvs commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +import getConversationActions from './components/getConversationActions';
done

2022-09-06 09:23 UTC, przemvs commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +                        // arrow
fixed, arrow not defined in this component, i extended this prop

2022-09-07 07:40 UTC, atomrc commented on src/script/page/RightSidebar/ConversationDetails/ConversationDetails.tsx
> +  const panelContentRef = useRef<HTMLDivElement>(null);
note for the future:
- let's migrate all `useFadingScrollbar` calls to an simple function that is passed to the `ref` attributes of elements. 

A `ref` + `hook` is not needed and not ideal

2022-09-07 07:40 UTC, atomrc approved these changes
Good job 💪

2022-09-07 08:03 UTC, merged