refactor: migrate Guest and Services Options to React
wireapp/wire-webapp pull request #13618
Opened 2022-09-07 09:54 UTC by przemvs

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-09-07 09:57 UTC, atomrc commented on src/script/page/RightSidebar/GuestServicesOptions/GuestServicesOptions.tsx
> +  // getLogger('GuestsAndServicesViewModel')
I think we can safely remove the `loggers` from new components. 
In the future we will try to have a less verbose more useful logging, but that can be done later
```suggestion
```

2022-09-07 09:58 UTC, atomrc commented on src/script/page/RightSidebar/RightSidebar.tsx
> +      // togglePanel(state, {entity: activeConversation});
???

2022-09-07 10:00 UTC, atomrc requested changes
Please add a few unit tests, no need to go too deep but at least basic coverage of the components

2022-09-07 10:02 UTC, przemvs commented on src/script/page/RightSidebar/RightSidebar.tsx
> +      // togglePanel(state, {entity: activeConversation});
This one will be fixed in https://github.com/wireapp/wire-webapp/tree/refactor/migrate-right-sidebar-to-react . This is what i said to you. Now we have to distinguish state from old functionality and new. It can take more time, so i'll decided to push changes to "epic" (https://github.com/wireapp/wire-webapp/tree/refactor/migrate-right-sidebar-to-react) and prepare functionality in this "epic".

2022-09-08 07:53 UTC, atomrc commented on src/script/page/RightSidebar/GuestServicesOptions/components/ServicesOptions/ServicesOptions.tsx
> +      {/*<p className="visibility-hidden">{t('servicesOptionsTitle')}</p>*/}
what to do with this?

2022-09-08 07:54 UTC, atomrc approved these changes

2022-09-08 08:53 UTC, merged