refactor: migrate AddParticipants to React
wireapp/wire-webapp pull request #13614
Opened 2022-09-06 21:34 UTC by przemvs

Panel switch functionality will be prepared on end of migration all panel elements, because we need to write additional functionality to be distinguished migrated and not migrated elements.

![image](https://user-images.githubusercontent.com/13432884/188744981-af25acd4-812f-4127-b9ee-aa5204959028.png)
![image](https://user-images.githubusercontent.com/13432884/188745008-85b4273b-80e2-4988-b50e-fa18a2bf7e55.png)

2022-09-07 09:44 UTC, arjita-mitra requested changes

2022-09-07 09:44 UTC, arjita-mitra commented on src/script/page/RightSidebar/AddParticipants/AddParticipants.tsx
> +        onGoBack={onBack}
Please talk to Astrid and confirm if you need to add these props for PanelHeader goBackTitle, title, closeBtnTitle

2022-09-07 09:51 UTC, przemvs commented on src/script/page/RightSidebar/AddParticipants/AddParticipants.tsx
> +        onGoBack={onBack}
Don't worry about it. It's prepared :D 

<img width="302" alt="image" src="https://user-images.githubusercontent.com/13432884/188848783-6b55c6f4-8535-4bd1-b8eb-9bc756e8c97a.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/13432884/188848813-4621f1d1-6a57-4df9-974f-4f13ab45068a.png">

2022-09-07 09:56 UTC, PatrykBuniX commented on src/script/page/RightSidebar/AddParticipants/AddParticipants.tsx
> +  const getUserEntities = useCallback(() => {
Is this function necessary here? We could just use `useMemo`, so there is no need to call this function on initial render (line 187) - we lose 1 rerender?

2022-09-08 07:32 UTC, przemvs commented on src/script/page/RightSidebar/AddParticipants/AddParticipants.tsx
> +  const getUserEntities = useCallback(() => {
Ahh.. sure, you're right. I'll fix it :)

2022-09-08 11:43 UTC, przemvs commented on src/script/page/RightSidebar/AddParticipants/AddParticipants.tsx
> +  const getUserEntities = useCallback(() => {
done.

2022-09-09 09:50 UTC, PatrykBuniX approved these changes
Looks fine 👍

2022-09-09 10:21 UTC, merged