refactor: migrate right-sidebar-to-react
wireapp/wire-webapp pull request #13613
Opened 2022-09-06 19:15 UTC by przemvs

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-09-29 15:07 UTC, atomrc requested changes

2022-09-29 15:07 UTC, atomrc commented on src/script/components/TitleBar/index.test.tsx
> +  // });
Some TODOs here

2022-09-29 15:07 UTC, atomrc commented on src/script/page/RightSidebar/PanelHeader/PanelHeader.tsx
> +  ref: ForwardedRef<HTMLButtonElement>,
Do we really need the `ref`? What is it for, I don't see a usage for it

2022-09-29 15:07 UTC, atomrc commented on src/script/page/RightSidebar/RightSidebar.tsx
> +        <Animated key={PanelState.CONVERSATION_DETAILS}>
you could factorize this and wrap the content in

```js
<Animated key={currentState}>
   {if currentSTate==== ...}
   {id currentState ===...}
</Animated>
...
```

2022-09-29 15:07 UTC, atomrc commented on src/style/foundation/framework.less
> +    position: absolute;
absolute 🤔  This seems a little weird. Is it for the animation?

2022-09-29 15:07 UTC, atomrc commented on src/script/page/RightSidebar/utils/toggleRightPanel.ts
> +
Wow this is scary. Isn't there a way to do this without querying the DOM? 
This is not going to go well if we change the ids/classes.

2022-09-29 15:19 UTC, przemvs commented on src/script/page/RightSidebar/utils/toggleRightPanel.ts
> +
If we merge all to react, we will change it for react statement ;)

2022-09-29 15:19 UTC, przemvs commented on src/style/foundation/framework.less
> +    position: absolute;
Yup, this is for animations

2022-09-29 15:19 UTC, przemvs commented on src/script/page/RightSidebar/RightSidebar.tsx
> +        <Animated key={PanelState.CONVERSATION_DETAILS}>
Animated can get only 1 children :)

2022-09-29 15:26 UTC, atomrc commented on src/style/foundation/framework.less
> +    position: absolute;
Can't we use `transform` instead of `position: absolute` can you explain why `absolute` is needed and why it's need here and not on the animation css code?

2022-09-29 15:26 UTC, atomrc commented on src/script/page/RightSidebar/RightSidebar.tsx
> +        <Animated key={PanelState.CONVERSATION_DETAILS}>
There is only going to be 1 child in the end (the panel that you are showing).

2022-09-29 19:56 UTC, przemvs commented on src/script/page/RightSidebar/PanelHeader/PanelHeader.tsx
> +  ref: ForwardedRef<HTMLButtonElement>,
removed.

2022-09-29 20:47 UTC, przemvs commented on src/script/components/TitleBar/index.test.tsx
> +  // });
fixed.

2022-09-29 21:31 UTC, przemvs commented on src/style/foundation/framework.less
> +    position: absolute;
sure, removed. I added only for animation and remove it after render.

2022-09-30 07:58 UTC, atomrc requested changes

2022-09-30 07:58 UTC, atomrc commented on src/script/view_model/panel/NotificationsPanel.tsx
> -  };
I think this accessibility code have disappeared from the new Notification component, please make sure the feature has been migrated

2022-09-30 08:18 UTC, przemvs commented on src/script/view_model/panel/NotificationsPanel.tsx
> -  };
discussed on a call about it

2022-10-03 16:46 UTC, atomrc approved these changes

2022-10-04 08:59 UTC, atomrc requested changes

2022-10-04 08:59 UTC, atomrc commented on setupTests.js
> +jest.mock('src/script/page/RightSidebar/utils/toggleRightPanel', () => () => jest.fn());
Please move this mock in the file that need it, if we mock it globally we will endup having weird behavior when we want to actually test it

2022-10-04 08:59 UTC, atomrc commented on src/script/components/TitleBar/index.test.tsx
> +    expect(onClick).not.toBe(false);
This test doesn't make sense, please restore the initial test

2022-10-04 08:59 UTC, atomrc commented on src/script/components/TitleBar/index.test.tsx
> +    // });
This test doesn't make sense, please restore the initial test

2022-10-04 08:59 UTC, atomrc commented on src/script/components/TitleBar/index.tsx
> +  }, []);
Can you add a comment here, I don't understand what this is for

2022-10-04 10:20 UTC, PatrykBuniX commented on src/script/page/RightSidebar/GroupParticipantUser/GroupParticipantUser.tsx
> +    amplify.subscribe(WebAppEvents.CONVERSATION.EVENT_FROM_BACKEND, checkMemberLeave);
unsubscribe? :D

2022-10-04 10:31 UTC, PatrykBuniX commented on src/script/page/RightSidebar/GroupParticipantUser/GroupParticipantUser.tsx
> +    amplify.subscribe(WebAppEvents.CONVERSATION.EVENT_FROM_BACKEND, checkMemberLeave);
unsubscribe? 😄

2022-10-04 10:36 UTC, PatrykBuniX commented on src/script/page/RightSidebar/RightSidebar.tsx
> +    amplify.subscribe(WebAppEvents.CONVERSATION.MESSAGE.UPDATED, (oldId: string, updatedMessageEntity: Message) => {
Unsubscribe?

2022-10-04 11:31 UTC, przemvs commented on src/script/components/TitleBar/index.tsx
> +  }, []);
added comment.

2022-10-04 11:43 UTC, przemvs commented on setupTests.js
> +jest.mock('src/script/page/RightSidebar/utils/toggleRightPanel', () => () => jest.fn());
moved

2022-10-04 11:44 UTC, przemvs commented on src/script/page/RightSidebar/GroupParticipantUser/GroupParticipantUser.tsx
> +    amplify.subscribe(WebAppEvents.CONVERSATION.EVENT_FROM_BACKEND, checkMemberLeave);
done

2022-10-04 11:46 UTC, przemvs commented on src/script/page/RightSidebar/RightSidebar.tsx
> +    amplify.subscribe(WebAppEvents.CONVERSATION.MESSAGE.UPDATED, (oldId: string, updatedMessageEntity: Message) => {
done.

2022-10-04 12:03 UTC, atomrc approved these changes

2022-10-04 12:05 UTC, PatrykBuniX approved these changes
👍

2022-10-05 08:40 UTC, atomrc requested changes

2022-10-05 08:40 UTC, atomrc commented on src/script/page/MainContent/MainContent.tsx
> +    [ContentViewModel.STATE.COLLECTION]: t('accessibility.headings.collection'),
Please revert to `ContentState` rather than `ContentViewModel.STATE`

2022-10-05 08:40 UTC, atomrc commented on src/script/page/MainContent/MainContent.tsx
> +  const {state, isFederated, initialMessage} = useKoSubscribableChildren(contentViewModel, ['state']);
Those are not observables, please revert the initial code

2022-10-05 08:50 UTC, przemvs commented on src/script/page/MainContent/MainContent.tsx
> +    [ContentViewModel.STATE.COLLECTION]: t('accessibility.headings.collection'),
done

2022-10-05 08:50 UTC, przemvs commented on src/script/page/MainContent/MainContent.tsx
> +  const {state, isFederated, initialMessage} = useKoSubscribableChildren(contentViewModel, ['state']);
done

2022-10-05 09:02 UTC, atomrc approved these changes

2022-10-05 09:03 UTC, merged