refactor: migrate GroupParticipantService to react
wireapp/wire-webapp pull request #13615
Opened 2022-09-07 06:47 UTC by przemvs

Panel functionality (swiping, switching panels, animations ) will be prepared when all panels will be migrated.

![image](https://user-images.githubusercontent.com/13432884/188824329-b8fe636b-62dd-45ac-9fa3-4ee77c4f1c77.png)

2022-09-07 09:36 UTC, arjita-mitra requested changes

2022-09-07 09:36 UTC, arjita-mitra commented on src/script/page/RightSidebar/GroupParticipantService/GroupParticipantService.tsx
> +    // this.onGoToRoot();
@przemvs why is this commented?
this.onGoToRoot();

2022-09-07 09:36 UTC, arjita-mitra commented on src/script/page/RightSidebar/GroupParticipantService/GroupParticipantService.tsx
> +
Please ask Astrid what should be the values for this properties like I have added in NotificationsPanel
goBackTitle, title, closeBtnTitle

@przemvs

2022-09-07 09:45 UTC, przemvs commented on src/script/page/RightSidebar/GroupParticipantService/GroupParticipantService.tsx
> +    // this.onGoToRoot();
You have described in description. This will be added if all panels will migrated. This panel PR's going to "epic" branch: [refactor/migrate-right-sidebar-to-react](https://github.com/wireapp/wire-webapp/tree/refactor/migrate-right-sidebar-to-react). And on this branch it will be prepared.

2022-09-07 09:46 UTC, przemvs commented on src/script/page/RightSidebar/GroupParticipantService/GroupParticipantService.tsx
> +
Please send me your changes.

2022-09-09 10:11 UTC, PatrykBuniX approved these changes

2022-09-09 10:13 UTC, merged