feat: implement collapsing left sidebar acc-62
wireapp/wire-webapp pull request #13791
Opened 2022-10-04 16:03 UTC by V-Gira

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-10-13 10:28 UTC, przemvs commented on src/script/page/AppMain.tsx
> +  const responsiveView = useResponsiveViewState(state => state.currentView);
I think you can use useAppMainState, add there for eg viewOptions

2022-10-13 10:28 UTC, przemvs commented on src/script/page/AppMain.tsx
> +            {(!smBreakpoint || responsiveView == 1) && (
I think it should be an enum

2022-10-13 10:28 UTC, przemvs commented on src/script/page/AppMain.tsx
> +            {(!smBreakpoint || responsiveView == 0) && (
I think it should be an enum

2022-10-13 10:28 UTC, przemvs commented on src/script/page/LeftSidebar/panels/Conversations/Conversations.tsx
> +    useResponsiveViewState.setState({currentView: 1});
I think it should be an enum

2022-10-13 10:28 UTC, przemvs commented on src/script/page/LeftSidebar/panels/Preferences.tsx
> +    useResponsiveViewState.setState({currentView: 0});
I think it should be an enum

2022-10-13 10:29 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/components/PreferencesPage.tsx
> +            onClick={() => setResponsiveView(1)}
I think it should be an enum

2022-10-13 10:29 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/components/PreferencesPage.tsx
> +        {smBreakpoint && responsiveView !== 1 && (
I think it should be an enum

2022-10-13 10:29 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/components/PreferencesPage.tsx
> +        {smBreakpoint && responsiveView !== 1 && (
I think it should be an enum

2022-10-13 10:30 UTC, przemvs commented on src/script/page/ResponsiveViewState.ts
> +  currentView: 1,
I think it should be an enum

2022-10-13 10:30 UTC, przemvs commented on src/script/page/ResponsiveViewState.ts
> +  currentView: Number;
I think you shoud use thiere ViewType

2022-10-13 10:31 UTC, przemvs commented on src/script/page/ResponsiveViewState.ts
> +enum viewType {
For naming enums we using PascalCase ;)

```suggestion
enum ViewType {
```

2022-10-13 10:31 UTC, przemvs commented on src/script/router/routerBindings.ts
> +    useResponsiveViewState.setState({currentView: 0});
Enum ? :)

2022-10-14 12:35 UTC, PatrykBuniX commented on src/script/components/InputBar/index.tsx
> +  // To be changed when design chooses a breakpoint, the conditional can be integrated to the ui-kit directly
👍

2022-10-14 13:01 UTC, PatrykBuniX approved these changes

2022-10-14 13:37 UTC, przemvs commented on src/script/components/TitleBar/TitleBar.tsx
> +  const setView = responsiveView.setCurrentView;
```suggestion
  const {setCurrentView: setView} = useAppMainState(state => state.responsiveView);
```

2022-10-14 13:39 UTC, przemvs commented on src/script/components/TitleBar/TitleBar.tsx
> +    setView(ViewType.LEFT_SIDEBAR);
I'll move to seperate function, e.g: `const setLeftSidebar = () => setView(ViewType.LEFT_SIDEBAR);`, and resue it :)

2022-10-14 13:40 UTC, przemvs commented on src/script/page/AppMain.tsx
> +  const showLeftSidebar = responsiveView.currentView == ViewType.LEFT_SIDEBAR;
```suggestion
  const {currentView} = useAppMainState(state => state.responsiveView);
  const isLeftSidebarVisible = currentView == ViewType.LEFT_SIDEBAR;
```

For me showLeftSidebar means to open it :)

2022-10-14 13:41 UTC, przemvs commented on src/script/page/LeftSidebar/panels/Conversations/Conversations.tsx
> +  const responsiveView = useAppMainState(state => state.responsiveView);
```suggestion
  const {setCurrentView} = useAppMainState(state => state.responsiveView);
```

2022-10-14 13:41 UTC, przemvs commented on src/script/page/LeftSidebar/panels/Conversations/Conversations.tsx
> +    responsiveView.setCurrentView(ViewType.LEFT_SIDEBAR);
```suggestion
    setCurrentView(ViewType.LEFT_SIDEBAR);
```

2022-10-14 13:41 UTC, przemvs commented on src/script/page/LeftSidebar/panels/Preferences.tsx
> +  const responsiveView = useAppMainState(state => state.responsiveView);
```suggestion
  const {setCurrentView} = useAppMainState(state => state.responsiveView);
```

2022-10-14 13:42 UTC, przemvs commented on src/script/page/LeftSidebar/panels/Preferences.tsx
> +    responsiveView.setCurrentView(ViewType.CENTRAL_COLUMN);
```suggestion
    setCurrentView(ViewType.CENTRAL_COLUMN);
```

2022-10-14 13:43 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/components/PreferencesPage.tsx
> +  const setResponsiveView = responsiveView.setCurrentView;
```suggestion
  const {currentView, setCurrentView} = useAppMainState(state => state.responsiveView);
  const isCentralColumn = currentView == ViewType.CENTRAL_COLUMN;
```

2022-10-14 13:43 UTC, przemvs commented on src/script/page/MainContent/panels/preferences/components/PreferencesPage.tsx
> +            onClick={() => setResponsiveView(ViewType.LEFT_SIDEBAR)}
```suggestion
            onClick={() => setCurrentView(ViewType.LEFT_SIDEBAR)}
```

2022-10-14 13:44 UTC, przemvs requested changes
Few changes :)

2022-10-14 14:09 UTC, V-Gira commented on src/script/page/AppMain.tsx
> +            {(!smBreakpoint || showLeftSidebar) && (
```suggestion
            {(!smBreakpoint || isLeftSidebarVisible) && (
```

2022-10-14 14:10 UTC, V-Gira commented on src/script/page/AppMain.tsx
> +            {(!smBreakpoint || !showLeftSidebar) && (
```suggestion
            {(!smBreakpoint || !isLeftSidebarVisible) && (
```

2022-10-14 14:41 UTC, przemvs commented on src/script/components/Modals/GroupCreation/GroupCreationModal.tsx
> +        {/* eslint jsx-a11y/no-autofocus : "off" */}
This is needed ?

2022-10-14 14:42 UTC, przemvs commented on src/script/components/TitleBar/TitleBar.tsx
> +            onClick={() => setLeftSidebar}
I think you can shorthand it onClick={setLeftSidebar}

2022-10-14 14:43 UTC, przemvs requested changes
1 comment and 1 change :)

2022-10-14 15:16 UTC, V-Gira commented on src/script/components/TitleBar/TitleBar.tsx
> +            onClick={() => setLeftSidebar}
done!

2022-10-14 15:20 UTC, V-Gira commented on src/script/components/Modals/GroupCreation/GroupCreationModal.tsx
> +        {/* eslint jsx-a11y/no-autofocus : "off" */}
That's only part of the PR because I removed the `StyledApp`wrapper.

We're keeping the `no-autofocus` eslint rule to remind us we should only use autofocus when it's required for accessibility.
(In this case, it's requested in the adesso review)

2022-10-17 12:22 UTC, przemvs approved these changes
LGTM :)

2022-10-17 12:23 UTC, merged