refactor: Migrate App initialization from knockout to React
wireapp/wire-webapp pull request #14033
Opened 2022-11-03 14:52 UTC by przemvs

Migrated Knockout rendering application to React.

Migrated with App-Loader, rendering content moved to id="wire-main".

2022-11-03 15:32 UTC, atomrc commented on src/script/main/app.ts
> +    // done.
???
```suggestion
```

2022-11-03 15:32 UTC, atomrc commented on src/script/main/app.ts
> +    // done.
```suggestion
```

2022-11-03 15:34 UTC, przemvs commented on src/script/main/app.ts
> +    // done.
Nice catch, forgot to remove it

2022-11-03 15:35 UTC, atomrc requested changes

2022-11-03 15:35 UTC, atomrc commented on src/script/main/app.ts
> +        await migrateToQualifiedSessionIds(this.repository.storage.storageService.db.sessions, context.domain ?? '');
The condition on `domain` is important here. We should never migrate with an empty domain!!!

2022-11-03 15:45 UTC, atomrc commented on src/page/index.ejs
> +    <div id="wire-app"></div>
Isn't it a problem that we have one extra wrapping div now? Is everything's good with scrolling or styling?

2022-11-03 15:47 UTC, atomrc commented on src/page/index.ejs
> -      data-uie-value="is-loading"
Is this migrated? I don't think I have seen those in the react component?

2022-11-03 20:09 UTC, przemvs commented on src/page/index.ejs
> +    <div id="wire-app"></div>
I didn't spot any problems

2022-11-03 20:26 UTC, przemvs commented on src/page/index.ejs
> -      data-uie-value="is-loading"
Added it ! :)

2022-11-04 07:40 UTC, PatrykBuniX commented on src/script/main/app.ts
> +      // this._showInterface();
what about this part?

2022-11-04 07:49 UTC, PatrykBuniX commented on src/script/page/AppMain.tsx
> +// registerReactComponent('app-container', AppMain);
to remove?

2022-11-04 12:35 UTC, przemvs commented on src/script/page/AppMain.tsx
> +// registerReactComponent('app-container', AppMain);
forgot :D

2022-11-04 12:36 UTC, przemvs commented on src/script/main/app.ts
> +      // this._showInterface();
Forgot to remove :D

2022-11-07 12:59 UTC, atomrc approved these changes

2022-11-07 13:01 UTC, merged