feat: New design for adding people
wireapp/wire-webapp pull request #14406
Opened 2022-12-30 15:50 UTC by przemvs

https://wearezeta.atlassian.net/browse/ACC-200

Added new design for selected people in adding to the group.

<img width="885" alt="image" src="https://user-images.githubusercontent.com/13432884/210088422-66bd4954-9c6a-4ca3-b5a9-6375bb33f769.png">

2023-01-02 08:54 UTC, arjita-mitra requested changes

2023-01-02 08:54 UTC, arjita-mitra commented on src/script/components/UserList/UserList.tsx
> +              <span css={collapseIcon(isSelectedContactsOpen)}>
Don't we need aria-hidden here?

2023-01-02 08:54 UTC, arjita-mitra commented on src/script/components/UserList/UserList.tsx
> +          <span css={collapseIcon(isContactsOpen)}>
Don't we need aria-hidden here?

2023-01-02 08:54 UTC, arjita-mitra commented on src/script/components/UserList/UserList.test.tsx
> +describe('UserList', () => {
Can you add some test for selected users functionality?

2023-01-02 09:30 UTC, PatrykBuniX commented on src/script/components/UserSearchableList.tsx
> +import {UserList} from './UserList/UserList';
Can't we shorten it to just `./UserList` as it was before?

2023-01-02 13:36 UTC, przemvs commented on src/script/components/UserSearchableList.tsx
> +import {UserList} from './UserList/UserList';
Hmm.. smth wrong with linter, i had error with this import.. but fixed :)

2023-01-02 14:23 UTC, przemvs commented on src/script/components/UserList/UserList.test.tsx
> +describe('UserList', () => {
added

2023-01-03 14:32 UTC, atomrc commented on src/script/components/list/ParticipantItem.tsx
> +import {UserlistMode} from 'Components/UserList/UserList';
```suggestion
import {UserlistMode} from 'Components/UserList';
```

2023-01-03 14:33 UTC, atomrc commented on src/script/page/LeftSidebar/panels/StartUI/PeopleTab.tsx
> +import {UserList, UserlistMode} from 'Components/UserList/UserList';
```suggestion
import {UserList, UserlistMode} from 'Components/UserList';
```

Isn't there a `index.js` file in there?

2023-01-03 14:34 UTC, atomrc commented on src/script/components/UserList/UserList.tsx
> +export enum UserListFolder {
Let's call those `sections` rather than `folders`

2023-01-12 15:10 UTC, V-Gira approved these changes

2023-01-16 11:19 UTC, przemvs commented
@atomrc I talked with Jann, and he said to merge this task to edge branch. Message from Jann:

> Could this be merged to edge or another env first? This way we would have a much better overview which tests are affected and will break

2023-01-16 11:23 UTC, atomrc commented
@przemvs sure, feel free to deploy to `edge` using this action https://github.com/wireapp/wire-webapp/actions/workflows/deploy-to-test-env.yml

2023-01-30 14:51 UTC, corodiak commented
Looks good from QA 👍

2023-01-31 10:38 UTC, arjita-mitra approved these changes

2023-01-31 10:39 UTC, merged