fix: Focus switches on new Messages (ACC-310)
wireapp/wire-webapp pull request #14606
Opened 2023-02-03 10:24 UTC by przemvs

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/ACC-310" title="ACC-310" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />ACC-310</a>  [Web] Focus switches on new Messages
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-02-03 10:46 UTC, thisisamir98 commented on src/script/hooks/useConversationFocus.ts
> + * Copyright (C) 2022 Wire Swiss GmbH
```suggestion
 * Copyright (C) 2023 Wire Swiss GmbH
```

2023-02-03 11:03 UTC, thisisamir98 approved these changes

2023-02-03 11:07 UTC, PatrykBuniX commented on src/script/components/list/ConversationListCell.tsx
> +  const isFocused = currentFocusId === conversation.id;
What about passing `isFocused` to this component? I don't think it needs to know what `currentFocusId` is, but rather if its focused or not.

2023-02-03 13:39 UTC, arjita-mitra commented on src/script/page/LeftSidebar/panels/Conversations/Conversations.tsx
> -          // personal user won't see availability status menu, on blur of the userName
why did you remove this code?

// personal user won't see availability status menu, on blur of the userName
          // conversation list should get the focus
          onBlur={() => focusConversationList(true)}

2023-02-06 07:38 UTC, przemvs commented on src/script/page/LeftSidebar/panels/Conversations/Conversations.tsx
> -          // personal user won't see availability status menu, on blur of the userName
Now first item of conversation always have a tabIndex = 0. So onBlur method is unnecessary. :)

2023-02-06 13:33 UTC, PatrykBuniX approved these changes

2023-02-06 15:11 UTC, arjita-mitra requested changes

2023-02-06 15:11 UTC, arjita-mitra commented on src/script/components/list/ConversationListCell.tsx
>    // always focus on the selected conversation when the folder tab loaded
/
<img width="1512" alt="Screenshot 2023-02-03 at 14 45 39" src="https://user-images.githubusercontent.com/28754444/216619024-1fe6c027-908c-49ae-b1ec-f2e480eef891.png">
/ always focus on the selected conversation when the folder tab loaded.

This condition is not working correctly anymore. Attached a screenshot where new group is focused when folder tab opened but the selected conversation is group1.

2023-02-07 15:04 UTC, przemvs commented on src/script/components/list/ConversationListCell.tsx
>    // always focus on the selected conversation when the folder tab loaded
Consulted with Rahil, We always focus from first conversation if we using Tab or Shift + Tab, also in Folders View and Conversations.

2023-02-07 16:14 UTC, arjita-mitra approved these changes

2023-02-07 16:15 UTC, merged