fix: Add error boundaries (SQSERVICES-1920)
wireapp/wire-webapp pull request #14728
Opened 2023-02-21 14:04 UTC by thisisamir98

Introduce error boundaries

2023-02-21 14:06 UTC, PatrykBuniX commented on package.json
> +    "react-error-boundary": "^3.1.4",
Lets use exact version (without `^`)

2023-02-21 14:13 UTC, atomrc commented on src/script/components/panel/UserDetails.tsx
> +    <ErrorBoundary FallbackComponent={ErrorFallback}>
In case this adds something to the DOM,cCan you check that this doesn't break the CSS flow?

2023-02-21 14:14 UTC, atomrc requested changes

2023-02-21 14:14 UTC, atomrc commented on src/script/components/panel/UserDetails.tsx
> +  const isFederated = user.isFederated;
Did you test this code? This is breaking since `user` doesn't have the `isFederated` property

2023-02-21 14:14 UTC, atomrc commented on src/script/components/panel/UserDetails.tsx
> +  const isGuest = !isFederated && user.isGuest;
Did you find where the `isGuest` is transformed from the participant object?

2023-02-21 14:15 UTC, tlebon commented on src/script/components/ErrorFallback.test.tsx
> +  throw new Error('failed to render');
this is a strange FC

2023-02-21 14:17 UTC, tlebon commented
do we have designs for the error boundary?

2023-02-21 14:23 UTC, atomrc commented on src/script/components/panel/UserDetails.tsx
> +  const isFederated = user.isFederated;
This PR should detect those mistakes automatically https://github.com/wireapp/wire-webapp/pull/14729

2023-02-21 14:36 UTC, thisisamir98 commented on src/script/components/panel/UserDetails.tsx
> +    <ErrorBoundary FallbackComponent={ErrorFallback}>
DOM is all fine, no changes.

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/63250054/220374367-f7cf95c3-2a30-4c3c-b63f-90b6309c0a72.png">

2023-02-21 14:40 UTC, thisisamir98 commented
@tlebon we will use modals and someone from design team will have a final look.

2023-04-04 08:48 UTC, atomrc approved these changes

2023-04-04 09:10 UTC, merged