[Draft] Reactions on Messages(sqservices -1734)
wireapp/wire-webapp pull request #14771
Opened 2023-03-02 17:38 UTC by arjita-mitra

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - As a Wire user I would like to have a wide range of reactions (emojis) at my disposal, so that I can use them to express myself in messages and reactions to messages.

- The **PR Description**
  - create message actions floating menu
  - integrate context menu, reply, emoji picker
  - manage action menu states focus/hover/selected
  - handle outside click
  - make everything keyboard accessible
  - unit testing
----
##### References
1. https://wearezeta.atlassian.net/browse/SQSERVICES-1734

2023-03-03 09:52 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/ContentMessage.tsx
> +    }
I think you can use shorter version :)
setActionMenuVisibility(isMessageFocused || msgFocusState)

2023-03-03 09:55 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/MessageActions/MessageReactions.tsx
> +  const [clientY, setPOSY] = useState(0);
Move this 0 above component, e.g. const INITIAL_CLIENT_X_POS = 0;

2023-03-03 09:57 UTC, przemvs commented on src/script/components/MessagesList/Message/ContentMessage/MessageActions/MessageReactions.tsx
> +      </button>
Please add smth like that as props also: data-stringify-emoji=":thumbsup:"

2023-03-19 13:55 UTC, arjita-mitra commented on src/script/components/MessagesList/Message/ContentMessage/ContentMessage.tsx
> +    }
with if, else its more readable so keeping it this way

2023-03-19 13:56 UTC, arjita-mitra commented on src/script/components/MessagesList/Message/ContentMessage/MessageActions/MessageReactions.tsx
> +      </button>
why do we need to add this prop?

2023-05-10 03:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=14771) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=14771) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: thisisamir98<br/>:x: arjita-mitra<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-webapp?pullRequest=14771) it.</sub>

2023-08-21 07:20 UTC, atomrc approved these changes

2023-08-21 07:21 UTC, atomrc requested changes

2023-08-21 07:21 UTC, atomrc commented on yarn.lock
Please delete that file, should be there

2023-08-21 07:25 UTC, atomrc commented on yalc.lock
> +{
This file shoundn't be commited, please remove

2023-08-21 07:34 UTC, merged