refactor: Fix typescript errors in mention rendering
wireapp/wire-webapp pull request #14869
Opened 2023-03-21 15:52 UTC by thisisamir98

refactored mentions

2023-03-21 17:35 UTC, comawill requested changes
Found one corner-case, that was not covered yet

2023-03-21 17:35 UTC, comawill commented on test/unit_tests/util/messageRendererSpec.js
> +        testCase: 'displays mention inside code block',
```suggestion
        testCase: 'mention does not affect code language',
```

2023-03-21 17:35 UTC, comawill commented on test/unit_tests/util/messageRendererSpec.js
> +        testCase: 'displays mention inside code block',
```suggestion
        testCase: 'mention does not affect url',
```

2023-03-21 17:35 UTC, comawill commented on test/unit_tests/util/messageRendererSpec.js
> +        testCase: 'displays mention inside code block',
```suggestion
        testCase: 'mention in title is displayed correctly',
```

2023-03-21 17:35 UTC, comawill commented on test/unit_tests/util/messageRendererSpec.js
> +        testCase: 'displays mention inside code block',
```suggestion
        testCase: 'mention works correctly as part of a link text',
```

2023-03-21 17:35 UTC, comawill commented on src/script/util/messageRenderer.ts
> -  const fixedTokens = fixCodeTokens(modifiedLinksTokens, originalTokens);
This code did nothing, but parse the markdown twice

2023-03-21 17:35 UTC, comawill commented on src/script/util/messageRenderer.ts
>        if (nextToken?.type === 'text') {
```suggestion
```
remove link.addrSet and the following if (it does nothing), but GitHub does not allow to select all unchanged lines

2023-03-21 17:35 UTC, comawill commented on src/script/util/messageRenderer.ts
>      if (!isWireDeepLink && !['autolink', 'linkify'].includes(link.markup)) {
```suggestion
    link.attrSet('href', href);
    if (!isWireDeepLink && !['autolink', 'linkify'].includes(link.markup)) {
```

2023-03-21 17:35 UTC, comawill commented on test/unit_tests/util/messageRendererSpec.js
>      ];
Please add testcase:
```javascript
  {
        expected:
        '<a href="http://wire.com#@you" target="_blank" rel="nofollow noopener noreferrer">http://wire.com#<div class="message-mention" data-uie-name="label-other-mention" data-user-id="pain-id" role="button"><span class="mention-at-sign">@</span>you</div></a>',
        mentions: [{length: 4, startIndex: 16, userId: 'pain-id'}],
        testCase: 'mentions don\'t affect auto-detected links',
        text: 'http://wire.com#@you',
      },
```

2023-03-23 11:31 UTC, atomrc approved these changes

2023-03-27 14:33 UTC, comawill approved these changes

2023-03-27 14:36 UTC, merged