refactor: Split ParticipantItem Component to separate components
wireapp/wire-webapp pull request #14874
Opened 2023-03-22 14:56 UTC by przemvs

2023-03-31 09:23 UTC, V-Gira commented on src/script/components/UserBadges/UserStatusBadges.styles.ts
> +  display: 'flex',
```suggestion
  display: 'flex',
  fill: 'var(--main-color)',
```
Currently, the icons are black in both light and dark mode

2023-04-03 07:55 UTC, atomrc commented on src/script/components/ParticipantItemContent/ParticipantItem.styles.ts
> +// };
What about this?

2023-04-03 07:55 UTC, atomrc commented on src/script/components/ParticipantItemContent/ParticipantItemContent.styles.ts
> +// };
what about this?

2023-04-03 07:55 UTC, atomrc commented on src/script/components/ParticipantItemContent/ParticipantItemContent.tsx
> +            {/*)}*/}
TODO

2023-04-03 09:21 UTC, przemvs commented on src/script/components/ParticipantItemContent/ParticipantItem.styles.ts
> +// };
removed.

2023-04-03 09:21 UTC, przemvs commented on src/script/components/ParticipantItemContent/ParticipantItemContent.tsx
> +            {/*)}*/}
removed.

2023-04-03 13:30 UTC, atomrc commented
Regression: 

Mic icon is not at the same position in calling participant list:

Before
![image](https://user-images.githubusercontent.com/1090716/229524424-b65f89b4-c37e-4948-b132-190e4449effb.png)

After 
![image](https://user-images.githubusercontent.com/1090716/229524516-5c2816be-1cf4-412b-9680-46207164b18b.png)

2023-04-03 13:35 UTC, atomrc requested changes
Regression:
- icons in the member's list are not aligned according to the previous design

changes

https://user-images.githubusercontent.com/1090716/229525695-5bb27a9b-3d78-4b96-82b8-dff92aea75b0.mov

2023-04-03 13:49 UTC, atomrc requested changes
Those icons have moved

https://user-images.githubusercontent.com/1090716/229529503-f1c6d22b-e17c-4b8d-8956-bc2783ac9891.mov

2023-04-03 14:52 UTC, atomrc commented on src/script/components/UserList/components/UserListItem/UserListItem.tsx
> +      <InViewport css={listItem(noInteraction)} onVisible={() => setIsInViewport(true)}>
```suggestion
      <div css={listItem(noInteraction)}>
```

2023-04-03 14:53 UTC, atomrc commented on src/script/components/UserList/components/UserListItem/UserListItem.tsx
> +      </InViewport>
```suggestion
      </div>
```

2023-04-04 12:24 UTC, atomrc approved these changes

2023-04-04 12:28 UTC, merged