featt: Use anchor tag for link preview
wireapp/wire-webapp pull request #15039
Opened 2023-04-19 08:42 UTC by p1gp1g

This allows one to use the browser's context
menu for instance to copy the link or open
it in a new window.

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We currently can't use the browser's context menu when a link is previewed. We can't copy/open in new (private) windows etc.

### Causes (Optional)

The link previews use a paragraph tag.

### Solutions

The link previews use an anchor tag.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-04-19 08:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=15039) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=15039) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-webapp?pullRequest=15039) it.</sub>

2023-09-06 14:46 UTC, p1gp1g commented
Gentle ping for this MR. The current behavior can be frustrating and the fix is very simple

2023-09-13 09:57 UTC, p1gp1g commented
@atomrc : Sorry if you are not the right person to contact, I didn't find the information on the README.

Almost every day, I have to look at the DOM of the application to copy links/open in private windows because the links are not in anchor tags. Do you think it is possible to review this PR ?

2023-09-13 10:21 UTC, atomrc requested changes

2023-09-13 10:21 UTC, atomrc commented on src/script/components/MessagesList/Message/ContentMessage/asset/LinkPreviewAssetComponent.tsx
> +                href={preview.url}
clicking the link preview (or that particular part that you modified) should open a new tab (not navigate out of Wire to that link).

```suggestion
                href={preview.url}
                target="_blank"  
                rel="noopener noreferrer"
```

2023-09-13 10:21 UTC, atomrc commented on src/script/components/MessagesList/Message/ContentMessage/asset/LinkPreviewAssetComponent.tsx
> +                href={preview.url}
Please use the `prependProtocol` function on the `preview.url` from `UrlUtil` to make sure the link has the right protocol. 

```
href={prependProtocol(preview.url)}
```

2023-09-13 10:22 UTC, atomrc commented
Hi @p1gp1g and thanks for your contribution 👌 

A few things to consider that I have added as a review. 

Thanks again and let me know if you have any question :)

2023-09-13 12:10 UTC, p1gp1g commented
Thanks for your review ! I have amended the commit with your changes

Note: noreferrer alone should be enough: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#noreferrer

2023-09-13 12:49 UTC, atomrc approved these changes
Approved 😎 
Thanks @p1gp1g

2023-09-13 12:49 UTC, merged