refactor: Improve re-rendering of classified bar
wireapp/wire-webapp pull request #15692
Opened 2023-08-30 15:47 UTC by atomrc

## Description

Since the classified bar was given the list of users from the parent component, it would force the parent component to re-render when the user list updates **even if the classified bar is not rendered**. 
This will make sure that updates that are only for the classified bar are only subscribed in the classified bar

## Screenshots/Screencast (for UI changes)

## Checklist

- [ ] PR has been self reviewed by the author;
- [ ] Hard-to-understand areas of the code have been commented;
- [ ] If it is a core feature, unit tests have been added;

2023-08-30 15:48 UTC, atomrc commented on src/script/components/calling/FullscreenVideoCall.tsx
> +  const {display_name: conversationName} = useKoSubscribableChildren(conversation, ['display_name']);
This component will not re-render when the list of users is updated

2023-08-30 15:49 UTC, atomrc commented on src/script/components/calling/CallingCell.tsx
>      'participating_user_ets',
This component will not re-render if the user list of the conversation changes

2023-08-30 18:57 UTC, przemvs requested changes

2023-08-30 18:57 UTC, przemvs commented on src/script/components/input/ClassifiedBar.tsx
> +}
**Suggestion:** I'll create common ClassifiedBarProps and extends ConversationClassifiedBar and UserClassifiedBar.

Example:

```
interface ClassifiedBarProps {
  classifiedDomains?: string[];
  style?: CSSObject;
  conversationDomain?: string;
}

interface UserClassifiedBarProps extends ClassifiedBarProps {
  users: User[];
}

interface ConversationClassifiedBarProps extends ClassifiedBarProps {
  conversation: Conversation;
}
```

2023-08-30 19:01 UTC, przemvs commented on src/script/components/input/ClassifiedBar.tsx
> +    <UserClassifiedBar
**Suggestion:** Prepare common ClassifiedBar component instead of use **UserClassifiedBar**. And same prepare component looks like ConversationClassifiedBar :)

2023-08-31 07:21 UTC, atomrc commented on src/script/components/input/ClassifiedBar.tsx
> +}
Done [f68c505](https://github.com/wireapp/wire-webapp/pull/15692/commits/f68c505cc2f2467d04a194c3916031ce30bcbcf3)

2023-08-31 07:26 UTC, przemvs approved these changes

2023-08-31 07:30 UTC, merged