feat: See E2EI certificate details [WPB-2213]
wireapp/wire-webapp pull request #15745
Opened 2023-09-06 05:41 UTC by przemvs

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-2213" title="WPB-2213" target="_blank"><img alt="Epic" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10807?size=medium" />WPB-2213</a>  5.3.25 See E2EI certificate details
  </td></table>
  <br />
 

## Description
Showing modal with PEM certificate chain. You can Download ( it will be prepared in another task ) or Copy to Clipboard this certificate.

* For now I'm using **TMP_CERTIFICATE** variable for display certificate, it will be removed while we have working functionality.

## Screenshots/Screencast (for UI changes)
![image](https://github.com/wireapp/wire-webapp/assets/13432884/f3ec2c99-40f5-4940-9dc5-d39a4d54db2a)

## Checklist

- [ ] PR has been self reviewed by the author;
- [x] Hard-to-understand areas of the code have been commented;
- [x] If it is a core feature, unit tests have been added;|

2023-09-06 15:49 UTC, V-Gira commented on src/script/components/Modals/CertificateDetailsModal/CertificateDetailsModal.test.tsx
> + * Copyright (C) 2022 Wire Swiss GmbH
```suggestion
 * Copyright (C) 2023 Wire Swiss GmbH
```
got em

2023-09-06 15:50 UTC, V-Gira commented on src/style/modal/certificate-details-modal.less
> + * Copyright (C) 2019 Wire Swiss GmbH
```suggestion
 * Copyright (C) 2023 Wire Swiss GmbH
```

2023-09-06 15:53 UTC, atomrc requested changes

2023-09-06 15:53 UTC, atomrc commented on package.json
> +    "@wireapp/api-client": "file:.yalc/@wireapp/api-client",
This is wrong, should not be commited

2023-09-06 15:53 UTC, atomrc commented on src/style/foundation/main.less
> +@import '../modal/certificate-details-modal';
Can we move that to a `styles.ts` file right next to the component?

2023-09-07 07:32 UTC, przemvs commented on package.json
> +    "@wireapp/api-client": "file:.yalc/@wireapp/api-client",
[795a769](https://github.com/wireapp/wire-webapp/pull/15745/commits/795a76903f327e95fdb75f6add7e911beefae124)

2023-09-07 07:32 UTC, przemvs commented on src/style/foundation/main.less
> +@import '../modal/certificate-details-modal';
[795a769](https://github.com/wireapp/wire-webapp/pull/15745/commits/795a76903f327e95fdb75f6add7e911beefae124)

2023-09-07 07:33 UTC, przemvs commented on src/style/modal/certificate-details-modal.less
> + * Copyright (C) 2019 Wire Swiss GmbH
[795a769](https://github.com/wireapp/wire-webapp/pull/15745/commits/795a76903f327e95fdb75f6add7e911beefae124)

2023-09-07 07:33 UTC, przemvs commented on src/script/components/Modals/CertificateDetailsModal/CertificateDetailsModal.test.tsx
> + * Copyright (C) 2022 Wire Swiss GmbH
[795a769](https://github.com/wireapp/wire-webapp/pull/15745/commits/795a76903f327e95fdb75f6add7e911beefae124)

2023-09-07 07:35 UTC, atomrc approved these changes

2023-09-07 08:33 UTC, merged