feat: E2EI SoftLock
wireapp/wire-webapp pull request #16406
Opened 2023-12-20 12:51 UTC by przemvs

## Description

## Screenshots/Screencast (for UI changes)

## Checklist

- [ ] PR has been self reviewed by the author;
- [ ] Hard-to-understand areas of the code have been commented;
- [ ] If it is a core feature, unit tests have been added;

### Important details for the reviewers

(Delete this section if unnecessary)

- use (x) data
- can be reviewed commit-by-commit
- be sure to look at ...

2023-12-20 13:18 UTC, atomrc requested changes

2023-12-20 13:18 UTC, atomrc commented on src/script/E2EIdentity/E2EIdentityEnrollment.ts
> +    const isFreshMLSSelfClient = void this.coreE2EIService.isFreshMLSSelfClient();
This is very weird, voiding the result of the function will always yield `undefined`

2023-12-20 13:25 UTC, przemvs commented on src/script/E2EIdentity/E2EIdentityEnrollment.ts
> +    const isFreshMLSSelfClient = void this.coreE2EIService.isFreshMLSSelfClient();
Yee.. I see, looking for issue :)

2023-12-21 10:50 UTC, atomrc commented on src/i18n/en-US.json
> +  "E2EI.SoftLock.Content": "Your team now uses end-to-end identity to make Wire’s usage more secure. The device verification takes place automatically using a certificate.<br /><br />Enter your ident
There should not be html in our translations. 
We should split this into multiple translation keys

2023-12-21 10:52 UTC, atomrc commented on src/script/E2EIdentity/E2EIdentityEnrollment.ts
> +        this.showE2EINotificationMessage(isFreshMLSSelfClient);
Let's save this info in the `config` (since it's passed to `initialize`) and avoid recomputing it (or do we need to recompute it at this point?)

2023-12-21 10:52 UTC, atomrc commented on src/script/E2EIdentity/E2EIdentityEnrollment.ts
> +          const isFreshMLSSelfClient = await this.coreE2EIService.isFreshMLSSelfClient();
can't we use the `freshMLSSelfClient` prop?

2023-12-21 10:53 UTC, atomrc commented on src/script/E2EIdentity/E2EIdentityEnrollment.ts
> +          const isFreshMLSSelfClient = await this.coreE2EIService.isFreshMLSSelfClient();
can't we use the `freshMLSSelfClient` prop?

2023-12-21 10:59 UTC, przemvs commented on src/i18n/en-US.json
> +  "E2EI.SoftLock.Content": "Your team now uses end-to-end identity to make Wire’s usage more secure. The device verification takes place automatically using a certificate.<br /><br />Enter your ident
It's not used. Forgot to remove it.

2023-12-21 11:29 UTC, przemvs commented on src/script/E2EIdentity/E2EIdentityEnrollment.ts
> +        this.showE2EINotificationMessage(isFreshMLSSelfClient);
done

2023-12-21 11:29 UTC, przemvs commented on src/script/E2EIdentity/E2EIdentityEnrollment.ts
> +          const isFreshMLSSelfClient = await this.coreE2EIService.isFreshMLSSelfClient();
done

2023-12-21 11:29 UTC, przemvs commented on src/script/E2EIdentity/E2EIdentityEnrollment.ts
> +          const isFreshMLSSelfClient = await this.coreE2EIService.isFreshMLSSelfClient();
done

2023-12-21 11:33 UTC, atomrc approved these changes

2024-01-02 11:31 UTC, merged