feat: add link to folders support page
wireapp/wire-webapp pull request #17214
Opened 2024-04-04 11:29 UTC by thisisamir98

## Description
Adds a link to support page for folders on sidebar

## Screenshots/Screencast (for UI changes)
<img width="204" alt="image" src="https://github.com/wireapp/wire-webapp/assets/63250054/703bbf14-2a18-4f6b-989b-df964f65d10f">

2024-04-04 11:32 UTC, aweiss-dev commented on src/script/page/LeftSidebar/panels/Conversations/ConversationTab/ConversationFolderTab.tsx
> +              dangerouslySetInnerHTML={{
Always feel a cold shiver when I see this in the code

2024-04-04 11:32 UTC, aweiss-dev approved these changes

2024-04-04 11:45 UTC, atomrc requested changes
Please use the `ReactLocalizerUtil` to translate string and transforms content into react components (thus avoiding the need for `dangerouslySetInnerHTML`)

2024-04-05 10:58 UTC, thisisamir98 commented on src/script/page/LeftSidebar/panels/Conversations/ConversationTab/ConversationFolderTab.tsx
> +              dangerouslySetInnerHTML={{
https://github.com/wireapp/wire-webapp/pull/17214/commits/5eab1f5c658f4522e2195ce8dcc5e13f1174a396

2024-04-05 11:02 UTC, przemvs commented on src/script/page/LeftSidebar/panels/Conversations/ConversationTab/ConversationFolderTab.tsx
> +              <a href={Config.getConfig().URL.SUPPORT.FOLDERS} target="_blank" rel="noreferrer">
You should use Link from react-ui-kit there :) Check another usages

2024-04-11 13:09 UTC, merged