feat: Delete group functionality
wireapp/wire-webapp pull request #7248
Opened 2019-09-06 14:44 UTC by AndyLnd

2019-09-06 14:48 UTC, ffflorian requested changes

2019-09-06 14:48 UTC, ffflorian commented on src/script/view_model/ActionsViewModel.js
> +      return new Promise(resolve => {
`resolve` is not used?

2019-09-06 14:48 UTC, ffflorian commented on src/script/view_model/panel/ConversationDetailsViewModel.js
> +      // TODO: Comment this out for the initial release, as there should only be support for handling the event in the beginning
TODO

2019-09-06 14:51 UTC, ffflorian approved these changes
LGTM

2019-09-06 14:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=7248) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=7248) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: AndyLnd<br/>:x: Andy<br/><hr/>**Andy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-webapp?pullRequest=7248) it.</sub>

2019-09-09 09:48 UTC, lipis approved these changes

2019-09-09 16:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=7248) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-webapp?pullRequest=7248) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: AndyLnd<br/>:white_check_mark: bennyn<br/>:x: Andy<br/><hr/>**Andy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-webapp?pullRequest=7248) it.</sub>

2019-09-09 16:35 UTC, merged