chore: Migrate CommonBindings to TS
wireapp/wire-webapp pull request #9512
Opened 2020-08-26 10:22 UTC by AndyLnd

2020-08-26 10:51 UTC, ffflorian requested changes

2020-08-26 10:51 UTC, ffflorian commented on src/script/view_model/bindings/CommonBindings.ts
>            $(this).css({backgroundImage: `url(${static_image})`});
We need to keep `function ()` here because two lines down we are using `this`.

2020-08-26 10:51 UTC, ffflorian commented on src/script/view_model/bindings/CommonBindings.ts
>            const item = $(this);
We need to keep `function ()` here because two in the next line we are using `this`.

2020-08-26 14:51 UTC, ffflorian requested changes

2020-08-26 14:51 UTC, ffflorian commented on src/script/view_model/bindings/CommonBindings.ts
> +type KOEvent<T = Event> = JQuery.Event & {currentTarget: Element; originalEvent: T};
Let's move the type above the comment since the comment belongs to the function below.

2020-09-04 14:51 UTC, lipis commented on src/script/view_model/bindings/CommonBindings.ts
>      const animated_gif = hoverable_item.data('hover');
while we at it camelCase?

2020-09-04 14:52 UTC, lipis commented on src/script/view_model/bindings/CommonBindings.ts
> +    let hide_timeout: number = undefined;
camelCase

2020-09-04 14:52 UTC, lipis approved these changes

2020-09-04 16:06 UTC, bennyn approved these changes

2020-09-07 09:45 UTC, merged