chore: Migrate EventService to TS
wireapp/wire-webapp pull request #9551
Opened 2020-08-31 14:38 UTC by AndyLnd

2020-08-31 14:48 UTC, ffflorian requested changes

2020-08-31 14:48 UTC, ffflorian commented on src/script/event/EventService.ts
> +        BaseError.TYPE.MISSING_PARAMETER as BASE_ERROR_TYPE,
```suggestion
        BASE_ERROR_TYPE.MISSING_PARAMETER,
```

2020-08-31 14:48 UTC, ffflorian commented on src/script/event/EventService.ts
> +        BaseError.TYPE.MISSING_PARAMETER as BASE_ERROR_TYPE,
```suggestion
        BASE_ERROR_TYPE.MISSING_PARAMETER,
```

2020-08-31 14:48 UTC, ffflorian commented on src/script/event/EventService.ts
>     * @returns {Promise} Resolves with the retrieved records
Please remove all type declarations from JSDoc.

2020-08-31 14:48 UTC, ffflorian commented on src/script/event/EventService.ts
> +    return this.logger.info('Updated asset message_et (uploaded)', primaryKey);
```suggestion
    this.logger.info('Updated asset message_et (uploaded)', primaryKey);
    return;
```

2020-08-31 14:48 UTC, ffflorian commented on src/script/event/EventService.ts
> +      return this.logger.warn('Did not find message to update asset (uploaded)', primaryKey);
```suggestion
      this.logger.warn('Did not find message to update asset (uploaded)', primaryKey);
      return;
```

2020-08-31 14:48 UTC, ffflorian commented on src/script/event/EventService.ts
> +  async updateEventSequentially(primaryKey: string, changes = {}): Promise<number> {
```suggestion
  async updateEventSequentially(primaryKey: string, changes: Object = {}): Promise<number> {
```

2020-08-31 14:48 UTC, ffflorian commented on src/script/event/EventService.ts
> +        // TODO: the second parameter of the transaction seems wrong, exie actually wants something of type `Dexie.Table` here
```suggestion
        // TODO: the second parameter of the transaction seems wrong, Dexie actually wants something of type `Dexie.Table` here
```

2020-08-31 14:52 UTC, ffflorian approved these changes

2020-09-04 14:54 UTC, lipis commented on src/script/conversation/ConversationRepository.ts
> +  private _addPrecedingEventsToConversation(events: EventRecord[], conversationEntity: Conversation) {
I think we tend to remove the leading underscore for private ones..

2020-09-04 14:55 UTC, lipis approved these changes

2020-09-07 10:44 UTC, merged