refactor: Migrate ConversationMapper to TypeScript
wireapp/wire-webapp pull request #9607
Opened 2020-09-07 23:24 UTC by bennyn

2020-09-08 12:38 UTC, ffflorian requested changes
Let's fix failing TypeScript first

2020-09-08 12:40 UTC, bennyn commented
Sure. I just converted the PR into a Draft.

2020-09-14 11:45 UTC, ffflorian approved these changes

2020-09-14 11:45 UTC, ffflorian commented on src/script/conversation/ConversationMapper.ts
> +        const updates: {[index: string]: any} = {
```suggestion
        const updates: Record<string, any> = {
```

2020-09-14 13:18 UTC, merged